### ISSUE TITLE
[feature](snap): did:polygonid

### ISSUE THREAD

**Issue by acrylicfiddle** [blockchain-lab-um/masca#216]
### Summary

Support PolygonID DID method and wallet-sdk. Happy to help with the integration and being the issuer/verifier node for you guys.

**Comment by Vid201** [comment]
> ### Summary
> Support PolygonID DID method and wallet-sdk. Happy to help with the integration and being the issuer/verifier node for you guys.
> 
> ### Expected behavior / User Story
> _No response_

Hey @acrylicfiddle , thanks for suggesting a feature.

Polygon DID method is indeed something we also looking into.

There is one caveat, though: the focus of this DID method is on zero-knowledge proofs, which is why Poygon uses Baby Jubjub Key, while secp256k1 is used in MetaMask. At the moment, Snaps enable only secp256k1 and Ed25519 key derivation. We are still investigating if there is a way to generate keys for the other elliptic curves from the existing seed phrase in the MetaMask (we want all keys derived from a single seed phrase, so you can back up keys and move to another device easily). If you have any more information, please share it with us! We are happy to work together to support did:polygon in Masca. :)

**Comment by Vid201** [comment]
This could be useful: https://docs.metamask.io/snaps/reference/rpc-api/#snap_getentropy
