### ISSUE TITLE
[proposal]: Account indices

### ISSUE THREAD

**Issue by Vid201** [blockchain-lab-um/masca#232]
### Motivation

Calculate account index based on `snap_getEntropy`.

### Proposal

Calculate account index in deterministic way.

**Comment by plesastapevka** [comment]
`snap_getEntropy` RPC accepts the following arguments:

```
const entropy = await snap.request({
  method: 'snap_getEntropy',
  params: {
    version: 1,
    salt: 'foo', // Optional
  },
});
```

New indices will be calculated based on the entropy returned from the `getEntropy` RPC method.

Since the entropy returned is 256-bit and the indices are 32-bit, we need to use the first/last 32 bits of the returned entropy -> potential collision shouldn't be a problem since the odds of collision are low. It would take approx. 77,163,000 generations of indices to get the same index twice.

Passing the currently selected account as:

```
const entropy = await snap.request({
  method: 'snap_getEntropy',
  params: {
    version: 1,
    salt: currentAccount
  },
});
```

should always return the same entropy for the currently selected account. Using this entropy we can derive private keys for the currently selected account which will be used for managing DIDs. This feature, when implemented, will be used in #233.
